fix: update walletconnect v2 packages
Uniswap/web3-react pull request #827
Opened 2023-06-09 13:03 UTC by JFrankfurt

<img width="1146" alt="image" src="https://github.com/Uniswap/web3-react/assets/5773490/1316051c-3e2d-493f-8099-8605c7ad3b31">

<img width="1159" alt="image" src="https://github.com/Uniswap/web3-react/assets/5773490/1efa0996-81e4-4315-8f48-8c102a8e8cfe">

2023-06-09 14:41 UTC, zzmp requested changes

2023-06-09 14:41 UTC, zzmp commented on example/package.json
> -  "version": "8.2.4",
Leave the versions, this is done by lerna as part of publishing.

2023-06-09 14:41 UTC, zzmp commented on yarn.lock
> +tslib@^2.0.0, tslib@^2.4.0, tslib@^2.5.0:
Can you dedup these?

2023-06-09 14:52 UTC, grabbou commented
LGTM, once @zzmp request is addressed

2023-06-12 14:16 UTC, grabbou approved these changes

2023-06-12 14:18 UTC, merged